### ISSUE TITLE
Assigning -1 to unsigned int

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#15]
`-1` is assigned to an unsigned int.

https://github.com/coderrect-inc/OpenRace/blob/d876b3fb347d5b38812c48d4d6840856aac714ef/src/PointerAnalysis/Util/GraphWriter.h#L175-L178

Is this a bug?

**Comment by bz-liu** [comment]
```edgeidx``` is the unsigned int in the warning/error.

This is not a bug, more like a flaw. I think Peiming just wants to distinguish the unexpected case:
```c
DTraits.getEdgeSourceLabel(Node, EI).empty() == true
```
so, when calling ```emitEdge()``` afterwards (```SrcNodePort == edgeidx```):
```c
  void emitEdge(const void *SrcNodeID, int SrcNodePort, const void *DestNodeID, int DestNodePort,
                const std::string &Attrs) {
    if (SrcNodePort > 64) return;              // Eminating from truncated part?
    if (DestNodePort > 64) DestNodePort = 64;  // Targeting the truncated part?

    O << "\tNode" << SrcNodeID;
    if (SrcNodePort >= 0) O << ":s" << SrcNodePort;
    O << " -> Node" << DestNodeID;
    if (DestNodePort >= 0 && DTraits.hasEdgeDestLabels()) O << ":d" << DestNodePort;

    if (!Attrs.empty()) O << "[" << Attrs << "]";
    O << ";\n";
  }
```
there should be no output when ```SrcNodePort == -1``` (```SrcNodePort``` is started and incremented from 0).

A fix is to change ```unsigned edgeidx``` to ```int edgeidx```.
Do you think so?

**Comment by BradSwain** [comment]
Yeah, sounds good to me. 
I agree not necessarily a bug, but at least we can get rid of the compiler warning.
