### ISSUE TITLE
False positive reported in DRB case 59

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#198]
**Describe the bug**
We report a race in dataracebench case 59, but there is no race in the code.

**Expected behavior**
No race should be reported.

**To Reproduce**
Run on dataracebench case 59.

**Additional context**
The only thing that looks different from other cases is the usage of `lastprivate`, but that shouldn't affect our analysis.
Some debugging will need to be done.

**Comment by RohanKheraCR** [comment]
DRB009 is the exact same except without lastprivate. In this case, a race is expected and reported. This means lastprivate should affect the analysis.
