### ISSUE TITLE
Enable compiler warnings by default

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#199]
**Is your feature request related to a problem? Please describe.**
Compiler warnings are currently turned off by default, because the number of warnings produced was too high.

**Describe the solution you'd like**
We should try to fix all the existing warnings and then enable the compiler warnings by default.

**Comment by bz-liu** [comment]
For now there is no compiler warnings. Do I change `OpenRace/.github/workflows/check-pr.yml` to include `-DENABLE_WARNING=True` and also update the doc (https://coderrect-inc.github.io/OpenRace/doc-setup-dev-env#building-openrace)?

**Comment by BradSwain** [comment]
Yes, Both those changes are perfect.

**Comment by BradSwain** [comment]
closed by #203
