### ISSUE TITLE
FN on DRB028

### ISSUE THREAD

**Issue by markbcahill** [coderrect-inc/OpenRace#229]
**Describe the bug**
OpenRace fails to detect one of the two data races described in DRB028. Specifically, it does not detect the race between a write on line 65 and a read on line 66.

**Expected behavior**
OpenRace detects a data race between two threads

**To Reproduce**
Run OpenRace on DRB028

**Additional context**
OpenRace successfully detects the race with a write on line 65 and itself.

**Comment by BradSwain** [comment]
Hi mark, DRB20 and 28 are known false negative cases.

We use an LLVM pass that unfortunately optimizes out the race.
```cpp
tmp =a [i]+i; a[i] = tmp;
```
under normal circumstances can be optimized to 
```cpp
a[i] = a[i]+i;
```
But in this case it also removes the data race.

Our pointer and array index analysis depends on the pass though, so for now there is not a clear solution.

**Comment by markbcahill** [comment]
Thanks for the responses! Sorry for the spam, Dr. Huang asked me to make issues for the bugs I found during my testing.

**Comment by BradSwain** [comment]
Closing this because issue #275 collects all the cases that fail due to optimization.
