### ISSUE TITLE
OpenRace does not report line numbers on DRB073

### ISSUE THREAD

**Issue by markbcahill** [coderrect-inc/OpenRace#230]
**Describe the bug**
The race report does not show line or character numbers for most of the races when OpenRace is run on DRB073. It instead shows 0.0. It does successfully point to 61.21.

**Expected behavior**
OpenRace reports the line and character numbers of the data races it detects.

**To Reproduce**
Run OpenRace on DRB073

**Additional context**

**Comment by BradSwain** [comment]
Thanks for reporting the issue.

This looks like something broke the debug info for this race. Most likely some preprocessing pass.
Someone will likely need to spend some time debugging to see exactly what went wrong.

**Comment by bz-liu** [comment]
Now openrace reports
```
integration/dataracebench/DRB073-doall2-orig-yes.c:61:0 integration/dataracebench/DRB073-doall2-orig-yes.c:61:21
```
where `61:0` matches the initial assignment to `j` in the loop
```
for (j=0;j<100;j++)
     ---
```
However, we miss the read of `j` by the comparison:
```
for (j=0;j<100;j++)
         -----
```
because we do not consider the IR of `cmp` as read:
```
%cmp2.i = icmp slt i32 %19, 99, !dbg !72 
```
so we are missing race pairs.

@BradSwain Do we update to consider the `cmp`?

**Comment by BradSwain** [comment]
The `cmp` should not be considered a read.

In the example shown above there should be a instruction before the `cmp` that looks something like

```llvm
%19 = load ...
```
and the load that creates `%19` should be considered as the read.

**Comment by bz-liu** [comment]
The related IRs for the index `j` are:
```
1  store i32 0, i32* %j, align 4, !dbg !64, !tbaa !62, !noalias !44 // -> j=0;
  ... 
2  %19 = load i32, i32* %j, align 4, !dbg !71, !tbaa !62, !noalias !44 // line 2-4 -> j++
3  %inc.i = add nsw i32 %19, 1, !dbg !71
4  store i32 %inc.i, i32* %j, align 4, !dbg !64, !tbaa !62, !noalias !44 
5  %cmp2.i = icmp slt i32 %19, 99, !dbg !72 // -> j<100
```
(about `icmp slt`, see https://releases.llvm.org/6.0.1/docs/LangRef.html#icmp-instruction)

The following are the comments from DRB073:
```
Data race pairs (we allow multiple ones to preserve the pattern):
  Write_set = {j@61:10, j@61:20}
  Read_set = {j@62:20, j@62:12, j61@:14, j61@:20}
  Any pair from Write_set vs. Write_set  and Write_set vs. Read_set is a data race pair.
```
where `j@61:10 ` is 

```
for (j=0;j<100;j++)
     ---
```
`j61@: 14` is 
```
for (j=0;j<100;j++)
         -----
```

`j@61:20` is 
```
for (j=0;j<100;j++)
               ---
```
Then in our report, we report this `%19 = load xxx` for both `j<100` and `j++`. Am I clear?

**Comment by BradSwain** [comment]
Yeah it seems so.

I think it is ok if we report a race on the read from `j++` but miss the race on `j<100`.
At IR level there is only one racing read and as long as we detect that one correctly I think it is ok.
