### ISSUE TITLE
Crash/infinite loop on CovidSim

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#264]
**Describe the bug**
In release mode the tool crashes, and in debug mode the tool runs for a long time (5+ hours) when scanning CovidSim.

**Expected behavior**
The tool should not crash or get stuck.

**To Reproduce**
Run openrace on the `CovidSim.ll` file attached

**Additional context**
When debugging, the code looks to get stuck inside the [worklist looop][1] inside of the `intraConstantProp` function in OMPConstantPropPass.cpp.

[1]: https://github.com/coderrect-inc/OpenRace/blob/078d8b6cbf9d9b0889ec79c158548a1dccaf45c8/src/PreProcessing/Passes/OMPConstantPropPass.cpp#L91

**Comment by addison-coderrect** [comment]
Fixed infinite loop in #277, new crash: hits unrecognisable function in RaceModel.cpp.

**Comment by VTCAKAVSMoACE** [comment]
This also affected at least GROMACS, which was what I was testing against.
