### ISSUE TITLE
Crash on Lulesh

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#270]
**Describe the bug**
Running OpenRace on lulesh results in a PTA crash.

**Expected behavior**
Should not crash.

**To Reproduce**
Build [lulesh][1] with openmp enabled using gllvm to get a whole program bc file. (or see attached file)
Run OpenRace on that bc.

[1]: https://github.com/LLNL/LULESH

**Comment by bz-liu** [comment]
Maybe instead of put the bc file on google drive, we can put it in a shared folder on our server. So everyone can use it directly? Or maybe I'm the only one that totally rely on the server?

**Comment by BradSwain** [comment]
They are also on our internal server under my home directory at `bcgen/bcs/`

**Comment by bz-liu** [comment]
There is no PTA crash now when running current commit (9a07760a21d059132faac4728b97f6893337d7db) against `/home/brad/bcgen/bcs/lulesh2.0.bc`. Close this issue.
