### ISSUE TITLE
Crash on GROMACS

### ISSUE THREAD

**Issue by addison-coderrect** [coderrect-inc/OpenRace#279]
**Describe the bug**
I'm unable to find a specific cause (ll or otherwise) for this issue, but GROMACS causes a crash in FSMemModel when [attempting to locate a memory block](https://github.com/coderrect-inc/OpenRace/blob/b0ec729e409c79a4b1623f61876a29baef0f10ec/src/PointerAnalysis/Models/MemoryModel/FieldSensitive/FSMemModel.h#L87).

**Expected behavior**
No crash should occur (should either return nothing or actually locate the memory block).

**To Reproduce**
Run GROMACS against [this PR](https://github.com/coderrect-inc/OpenRace/pull/277).

**Comment by bz-liu** [comment]
Do you know which one is the .bc file for GROMACS on our drive should I use to reproduce this bug? @addison-coderrect

**Comment by addison-coderrect** [comment]
libgromacs.so.6.0.0.bc is the one tested against.

**Comment by bz-liu** [comment]
Does GROMACS have a main function?

**Comment by bz-liu** [comment]
The problem is a case PTA does not consider: 
when initializing global vars (`FSMemModel::processScalarGlobals`) and the constant global expr is a complicated expression, e.g., bitcast: we cannot use `getMemBlock` to find its allocated object, we need to see what is the operator then to check which is the object we want in the operation.

**Comment by bz-liu** [comment]
(I feel my previous update was missing in this issue ... GitHub did so, don't know why ...) 
After I fixed this issue, I got the error msg: 
```Fatal Error: 'main' function cannot be found!```

Is there a main in the .bc? I just found the function with name `gmx_run_cmain`.

**Comment by BradSwain** [comment]
There should be a main function at `gmx.cpp:51`

**Comment by bz-liu** [comment]
I cannot find the file `gmx.cpp` from https://github.com/gromacs/gromacs, did we use this source? If there is other problem related to gromacs and this crash, please comment here.

**Comment by BradSwain** [comment]
I didn't realize there is a public github repo. I have been downloading the source from their [website](https://manual.gromacs.org/).

But on the github repo here is the main I mentioned before:

https://github.com/gromacs/gromacs/blob/8dd21f717c82277c611b537d92c19348ded5b357/src/programs/gmx.cpp#L51

**Comment by bz-liu** [comment]
My intuition is to search GitHub. 
I'll take a look why main is missing.
