### ISSUE TITLE
OpenRace gets stuck on an endless loop on DRB074

### ISSUE THREAD

**Issue by markbcahill** [coderrect-inc/OpenRace#296]
**Describe the bug**
Upon running OpenRace on DRB074 in the most recent docker image, the tool gets stuck in an endless loop, continuously outputting `Unhandled OpenMP call: __kmpc_flush`

**Expected behavior**
OpenRace successfully runs on DRB074

**To Reproduce**
Run OpenRace on DRB074

**Additional context**

**Comment by BradSwain** [comment]
Thanks for reporting this.

It looks like an `llvm_uncreachable` statement is being executed, and in release mode it causes the program to hand for some reason.

https://github.com/coderrect-inc/OpenRace/blob/4ab6e06f3e695578fe17fb8926f6732123837264/src/IR/Builder.cpp#L220

I will try to add a regression test and push a fix.
