### ISSUE TITLE
Missing Debug info on Lulesh

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#308]
**Describe the bug**
~14k races are skipped in lulesh because of broken debug info

**Expected behavior**
This is a very high number of races skipped due to missing debug info.  Something is likely going wrong.

**To Reproduce**
```shell
./bin/openrace --print-trace=false ulesh2.0.bc
```

**Comment by bz-liu** [comment]
The .bc and .ll need to be built with debug info, since there is no debug info included.
