### ISSUE TITLE
Add simple reporter

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#309]
**Is your feature request related to a problem? Please describe.**
Up until now our race report has just included the file location and LLVM IR instructions causing the race.

```llvm
haloExchange.c:635:24 haloExchange.c:623:24
	  store i32 %96, i32* %97, align 4, !dbg !1683, !tbaa !1617
	  %39 = load i32, i32* %38, align 4, !dbg !1641, !tbaa !1617
```

In many cases identical races are reported duplicate times (e.g. r/w and r/w race).
There is also no information about how the racing lines were reached (e.g. callstack).

This makes it difficult to identify True and False positives (TP/FP) on projects larger than a micro benchmark. 

**Describe the solution you'd like**
We should add a simple reporter that prints **unique** races to the terminal in a way that we (developers of the tool) are able to determine if the race is a TP or FP.

For each reported race the following should be shown:
 1. file location for each access (e.g. `file.c:line:col`)
 2. LLVM IR inst for each access
 3. Callstack for each access

If the call stack for the accesses is mostly the same, the common part can be displayed only once.
Maybe something like:

```shell
compute.c:32:15 compute.c36:15
  store i32 %x, i32* %shared
  store i32 %y, i32* %shared
(Common Callstack)
main
omp_outlined
(Access 1 Callstack)
assign_x
(Access 1 Callstack)
assign_y
```

**Additional context**
Later we will design a fully featured reporter for reporting races to the user.
This reporter can be considered for developer use only and does not need to be very fancy.

**Comment by bz-liu** [comment]
For a **unique** race, what if two pairs of races share the same file locations for each access, but different call stacks? A more drama case is one of the race is TP but the other is FP due to infeasible call stacks?

**Comment by BradSwain** [comment]
I hadn't thought of that. In that case I think it makes sense to  report the race twice.
