### ISSUE TITLE
Add pthread support

### ISSUE THREAD

**Issue by funemy** [coderrect-inc/OpenRace#32]
Use this to track our Pthread Support

**Known pthread Features**
 - [X] fork/join
 - [X] lock/unlock
 - [X] spinlock
 - [ ] once
 - [ ] rwlock
 - [ ] barrier
 - [ ] cond/signal/wait
 - [ ] kill
 - [ ] cancel

**Comment by BradSwain** [comment]
Only focusing on OpenMP for now.
