### ISSUE TITLE
Interest in Working with OpenRace

### ISSUE THREAD

**Issue by davis-matthew** [coderrect-inc/OpenRace#326]
Hello OpenRace Team,

I am currently working on a project combining static and dynamic analysis for race detection and verification on CPU & GPU programs. I am interested in using OpenRace as the static analysis component, because my current static analyzer is out of date and produces faulty results. 

Is there documentation available about the support status for each OpenMP pragma/feature (ex. target offloading)? I would like to help implement new features/improve analysis quality if I can while working with the tool.

**Comment by BradSwain** [comment]
I will add a page showing our support for different OpenMP features.

**Comment by BradSwain** [comment]
It hasn't been merged yet, but you can see the markdown for the page I added: https://github.com/coderrect-inc/OpenRace/pull/327/files

If you have any questions or think anything deserves more detail, I am happy to help.

Also, feel free to open issues or PR for anything you come across while working with the tool.
