### ISSUE TITLE
Coderrect doesn't locate data race in example pi.c

### ISSUE THREAD

**Issue by saif-ilshat** [coderrect-inc/OpenRace#70]
**Describe the bug**
Coderrect doesn't locate data race in example pi.c, it prints No race detected, screenshot attached.
I'm using gcc-7.1

**Expected behavior**
Reported data racein `sum+=`

**To Reproduce**
Run Coderrect  with example pi.c

**Additional context**
![coderrect_pi](https://user-images.githubusercontent.com/82016444/113664645-88a26580-96c5-11eb-85c5-096a3a218504.png)

**Comment by funemy** [comment]
Hi!
Thanks for trying our tool.
The bug you are reporting is weird -- I cannot reproduce it on my machine with v1.0.0 and the tool correctly report the race.

Could you provide us more details to help us understand the problem? such as:
1. What OS you are on?
2. Can you share the logs? It's placed under `.coderrect/logs/log.current`

**Comment by saif-ilshat** [comment]
> Hi!
> Thanks for trying our tool.
> The bug you are reporting is weird -- I cannot reproduce it on my machine with v1.0.0 and the tool correctly report the race.
> 
> Could you provide us more details to help us understand the problem? such as:
> 
> 1. What OS you are on?
Red Hat Enterprise Linux Server release 6.4 (Santiago)
Linux 2.6.32-358.el6.x86_64 

> 2. Can you share the logs? It's placed under `.coderrect/logs/log.current`
I have no log here /nfs/soft/bos/coderrect-linux-hpc-1.0.0/logs

**Comment by funemy** [comment]
@saif-ilshat 
Ah sorry, I was not being clear enough.

The log file will be generated under the folder where you run coderrect.
So in your case, it's `<path to pi.c>/.coderrect/logs/log.current`

**Comment by saif-ilshat** [comment]
I think problem is here (full log in attachment)
19:29:47 [warning] [coderrect-clang] [utils.go:53:shared.execCmd] Failed to execute a command. out=/nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang)
/nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang)
/nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /nfs/soft/bos/coderrect-linux-hpc-1.0.0/clang/bin/clang)
    

[log.current.txt](https://github.com/coderrect-inc/OpenRace/files/6286031/log.current.txt)

**Comment by funemy** [comment]
@saif-ilshat 
Thanks for providing the logs -- what you highlighted above is indeed the cause of the problem.

I've tried to create a coderrect package on RHEL6.4, however, the system is a bit too old for us to support, and there are some non-trivial issues to get coderrect built.

As for now, the solutions I can give is to either try the tool on a newer Linux version -- coderrect works on ubuntu >=14.04
, or a system with at least glibc version 2.17

The other way is to build a newer version of glibc (and maybe glibcxx as well) on you own, and pass the new glibc path to `LD_LIBRARY_PATH`. This [post](https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos) could potentially be a good resource to look at.

**Comment by saif-ilshat** [comment]
Thanks a lot! I will try coderrect on newer Linux.

**Comment by funemy** [comment]
> Thanks a lot! I will try coderrect on newer Linux.

No problem! And if you are interested, here is the [link](https://public-installer-pkg.s3.us-east-2.amazonaws.com/coderrect-linux-develop.tar.gz) for our develop package, which includes quite some changes after 1.0.0.
