### ISSUE TITLE
Dump reports to JSON

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#8]
The current [`Report`](https://github.com/coderrect-inc/OpenRace/blob/develop/src/Reporter/Reporter.h) functionality is really basic. We should probably completely rewrite it at some point. For now, a good starting place it to be able to dump race reports to JSON.

Pick a json library and add it as a dependency to our [conanfile](https://github.com/coderrect-inc/OpenRace/blob/develop/conanfile.txt). [jsoncpp](https://conan.io/center/jsoncpp) looks to be the most popular and is probably a good choice.

Then add a function that dumps the race report in json format.

**Comment by tamugang** [comment]
A follow-up question: do we have a plan to implement a better report viewer?
Yes or not, we need to consider what kind of information to include in the JSON report, from the perspective of presenting those races.

**Comment by BradSwain** [comment]
> A follow-up question: do we have a plan to implement a better report viewer?

Not sure. Outside the scope of this project for now, at least until this repo is closer to matching the functionality of the existing tool.

>  we need to consider what kind of information to include in the JSON report

I agree. I think from the report side, we should include as much information as is reasonable and leave the display of that info to something else (for now).

At a minimum we should dump information about the location of the race, and the names of the racing variables (as the existing tool does).

Some additional info we could potentially dump to JSON:
- Locks held
- Program path leading to race access

and probably a lot more.

**Comment by BradSwain** [comment]
Closing this one to use #58 instead
