### ISSUE TITLE
Support OpenMP Master

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#91]
OpenMP Master is used to ensure a code block is only executed by the master thread within an OpenMP team.

```cpp
int global;

#pragma omp parallel
{
  #pragma omp master
  {
    global++;
  }
}
```

Without `omp master`, there will be a  data race on `global++`. But with `omp master` the race is prevented.
Check dataracebench cases [103](https://github.com/LLNL/dataracebench/blob/master/micro-benchmarks/DRB103-master-orig-no.c) and [124](https://github.com/LLNL/dataracebench/blob/master/micro-benchmarks/DRB124-master-orig-yes.c) for two more examples of `omp master`.

Also see the [OpenMP specification on master](https://www.openmp.org/spec-html/5.0/openmpse24.html#x118-4380002.16)

A PR supporting OpenMP master should:
 - [x] Add recognizer(s) to LanguageModel/OpenMP.h
 - [x] Add the appropriate IR type to IR/IR.h
 - [x] Add the new Omp master IR to the function summary in IR/Builder.cpp
   - [x] Add a unit test checking that the IR is added to the summary correctly in tests/unit/IR/OpenMPIR.test.cpp
 - [ ] Ensure the IRType is converted to an trace event in Trace/ThreadTrace.cpp
   - [ ] Add a unit test checking this in Trace/OpenMPTrace.test.cpp
 - [x] Update and Analyses as needed
 - [x] Add integration tests checking openmp master is handled correctly
   - [x] DRB103 in tests/integration/dataracebench.cpp
   - [ ] DRB124 in tests/integration/dataracebench.cpp

One trick that might work for modeling `omp master` is to only the events inside of an `omp master` block to the first thread per OpenMP team. This should match the functionality of OpenMP master exactly.

There will be two identical thread traces for each omp parallel region in our ProgramTrace. 
If we can identify:
 1. Which thread is the "second" omp thread
 2. Which instructions are within a omp master block
We can simply skip adding any instructions inside of an omp master block to the second thread.

**Comment by jedishao23** [comment]
I think the logic and functionality of OpenMP **master** is kind of like the **single** construct with **nowait** clause, which is not yet supported by the tool. So maybe these two problems can be fixed at the same time.

**Comment by addison-coderrect** [comment]
Yeah, I've noticed an issue with the existing thread traces which is preventing this (might be unrelated to what @jedishao23 is referencing); the `omp_if.end` basic block instructions are not being picked up for some reason. Instead, it's just `llvm.dbg.value` as the sole instruction. Still trying to work out the cause of that.

**Comment by addison-coderrect** [comment]
I don't believe this change requires a separate IRType conversion (re: how single is implemented). I can add it if desired, though.

**Comment by addison-coderrect** [comment]
IRType is not necessary and DRB124 fails due to LLVM optimisation.

**Comment by jedishao23** [comment]
Yeah, I get your point. This implementation makes the **master** construct similar to the **single** construct. But I think there have some differences between **master** and **single**. The **single** construct has an implicit barrier, while the **master** doesn't have it. This is also the main reason why DRB124 has a data race and DRB125 has no race. However, I think this implementation may not consider the barrier.

**Comment by addison-coderrect** [comment]
Concerningly, a targeted test showed that that race condition was picked up. Makes me wonder about openmp-single...

**Comment by BradSwain** [comment]
@jedishao23 you are correct. I believe the barrier after single will be explicit in the IR.

E.g., there will be a barrier statement after the `kmpc_end_single` call

https://github.com/coderrect-inc/OpenRace/blob/587f9ab2633f650a777c0e99dc60185cda3077db/tests/data/integration/dataracebench/DRB125-single-orig-no.ll#L83-L89

**Comment by addison-coderrect** [comment]
Confirmed by #132.

**Comment by funemy** [comment]
> 
> 
> Confirmed by #132.

Can you be more explicit what are you trying to confirm in #132?

The PR suggests all tests passed (I assume it includes the one you just added)

And I think it's correct we report no race in your new test cases.
So everything looks fine?

**Comment by addison-coderrect** [comment]
> Can you be more explicit what are you trying to confirm in #132?

#132 is effectively [DRB125](https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB125-single-orig-no.c) compared to https://github.com/coderrect-inc/OpenRace/pull/128/commits/9f71275737a47d08ad6e0099a7db3b8a5868d98d which is [DRB124](https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB124-master-orig-yes.c) (but without the LLVM optimiser nuking the used variable in the parallel blocks). I was confirming that we weren't affected by the bug @jedishao23 was suggesting.
