### ISSUE TITLE
Support OpenMP threadprivate

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#93]
OpenMP threadprivate makes a peice of data local to each thread.
```cpp
int global = 0;
#pragma omp threadprivate(global)

#pragma omp parallel
{
    global++;
}
```

Without `omp threadprivate`, there will be a  data race on `global++`. But with `omp threadprivate` the race is prevented.
Check these [dataracebench](https://github.com/LLNL/dataracebench/tree/master/micro-benchmarks) cases for more examples of threadprivate:
 - 85
 - 86
 - 87
 - 91
 - 102
 - 171

Also see the [OpenMP specification on threadprivate](https://www.openmp.org/spec-html/5.0/openmpsu104.html#x137-5470002.19.2)

I'm less sure how to handle threadprivate correctly, as it depends on how it gets translated to LLVM IR.
I think it will have something to do with [LLVM's thread local storage](https://llvm.org/docs/LangRef.html#thread-local-storage-models).

Thread local variables should always be race free, so if we can recognize an access to a thread local variable, we can simply skip it, similar to how we handle [atomic accesses](https://github.com/coderrect-inc/OpenRace/blob/815aed47c6c5a7dccd1672a6d58ee8f3dc8e455c/src/IR/Builder.cpp#L66).

In addition to supporting threadprivate, a PR for this issue should add tests ensuring it is handled correctly.
At a minimum add tests for:
 - [x] function summary being built correctly (IR/Builder.cpp)
 - [x] relevant dataracebench cases being handled correctly (tests/integration/dataracebench.test.cpp)
 - [ ] Additional integration tests testing threadprivate specifically

**Comment by addison-coderrect** [comment]
Implemented with LLVM [GlobalValue::isThreadLocal](https://llvm.org/doxygen/classllvm_1_1GlobalValue.html#a239427c2c3a01e23bd15b29633696536); additional integration tests aren't necessary as implementation does not rely on openrace IR.

**Comment by BradSwain** [comment]
Completed in #124
